# GPIMimo configuration file

# Number of processes for running R in parallel
np = 4

# Energy range (in % of mean energy) for which time-of-flight variations are minimized.
# E.g. range_E = 10 means -5 % .. +5 %
range_E = 10

# Number of repetitions
n_repeats = 10

# Response variables
[responses]
1 = {Name = "Resolving power", Target = 10000, Weight = 1}

# Factors
# Note: between 3 and 7 factors need to be enabled
[factors]
1  = { Name = "v1", Enabled = 1, Transformation = "V1", Range = 0.02, LowLimit = 0, HighLimit = 1.5 }
2  = { Name = "v2", Enabled = 0, Transformation = "V2", Range = 0.02, LowLimit = 1, HighLimit = 1.5 }
3  = { Name = "z1", Enabled = 0, Transformation = "Z1", Range = 0.02, LowLimit = 0, HighLimit = 10 }
4  = { Name = "z2", Enabled = 0, Transformation = "Z2", Range = 0.02, LowLimit = 0, HighLimit = 10 }
5  = { Name = "l", Enabled = 1, Transformation = "L", Range = 0.02, LowLimit = 0, HighLimit = 10 }

# Controls
[controls]
1  = { Name = "V1", Transformation = "v1", StartValue = 1.1 }
2  = { Name = "V2", Transformation = "v2", StartValue = 0.9 }
3  = { Name = "Z1", Transformation = "z1", StartValue = 0.7 }
4  = { Name = "Z2", Transformation = "z2", StartValue = 1.7 }
5  = { Name = "L", Transformation = "l", StartValue = 2 }

