# PIMo configuration file

# Number of processes for running R in parallel
np = 4

# Energy range (in % of mean energy) for which time-of-flight variations are minimized.
# E.g. range_E = 10 means -5 % .. +5 %
range_E = 10

# Number of repetitions
n_repeats = 10

# Response variables
[responses]
1 = {Name = "Resolving power", Target = 1e6, Weight = 1}

# Factors
# Note: between 3 and 7 factors need to be enabled
[factors]
01 = { Name = "v1", Enabled = 1, Transformation = "V1", Range = 0.02, LowLimit = 0, HighLimit = 1.5 }
02 = { Name = "v2", Enabled = 0, Transformation = "V2", Range = 0.02, LowLimit = 0, HighLimit = 2 }
03 = { Name = "v3", Enabled = 0, Transformation = "V3", Range = 0.02, LowLimit = 0, HighLimit = 2 }
04 = { Name = "v4", Enabled = 1, Transformation = "V4", Range = 0.02, LowLimit = 1, HighLimit = 2 }
05 = { Name = "z1", Enabled = 1, Transformation = "Z1", Range = 0.02, LowLimit = 0, HighLimit = 10 }
06 = { Name = "z2", Enabled = 0, Transformation = "Z2", Range = 0.02, LowLimit = 0, HighLimit = 10 }
07 = { Name = "z3", Enabled = 0, Transformation = "Z3", Range = 0.02, LowLimit = 0, HighLimit = 10 }
08 = { Name = "z4", Enabled = 1, Transformation = "Z4", Range = 0.02, LowLimit = 0, HighLimit = 1 }
09 = { Name = "l", Enabled = 0, Transformation = "L", Range = 0.01, LowLimit = 0, HighLimit = 10 }
10 = { Name = "d5", Enabled = 0, Transformation = "D5", Range = 0.01, LowLimit = 0, HighLimit = 10 }
11 = { Name = "u5", Enabled = 0, Transformation = "U5", Range = 0.01, LowLimit = 0, HighLimit = 10 }

# Controls
[controls]
01 = { Name = "V1", Transformation = "v1", StartValue = 0.8 }
02 = { Name = "V2", Transformation = "v2", StartValue = 0 }
03 = { Name = "V3", Transformation = "v3", StartValue = 0 }
04 = { Name = "V4", Transformation = "v4", StartValue = 1.2 }  # end cap voltage
05 = { Name = "Z1", Transformation = "z1", StartValue = 0.4 }
06 = { Name = "Z2", Transformation = "z4", StartValue = 0 }  # set to z4 if less than four mirror elements are used.
07 = { Name = "Z3", Transformation = "z4", StartValue = 0 }  # set to z4 if less than five mirror elements are used.
08 = { Name = "Z4", Transformation = "z4", StartValue = 0.9 }
09 = { Name = "L", Transformation = "l", StartValue = 1 }
10 = { Name = "D5", Transformation = "d5", StartValue = 0 }
11 = { Name = "U5", Transformation = "u5", StartValue = 0 }
